config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'pages/anya'
  resources :user_sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create]
  match '*path', to: 'application#not_found_method', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password :password, validations: true
  validates :name, presence: true, uniqueness: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :is_anya

  def current_user
    # If session[:user_id] is nil, set it to nil, otherwise find the user by id.
    @current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end

  def is_anya
    if current_user && current_user.name == 'anya'
      @is_anya = true
    end
  end

  def not_found_method
    render :file => "#{Rails.root}/public/404.html", layout: false, status: 404
  end
end

app/controllers/pages_controller.rb
require 'base64'

class PagesController < ApplicationController
  
  # index is a public page
  def index
    begin
      anya_path = Rails.application.config.anya_dir
      image = (anya_path + params.fetch(:img, 'anya.png')).gsub("../", "")
      file = File.open(image)
      @img = Base64.encode64(file.read)
      file.close
      
      @anyas = []
      anya_pattern = anya_path + '*.txt'
      Dir.glob(anya_pattern) do |filename|
        anya = File.open(filename)
        @anyas.append(anya.read)
        anya.close
      end
    rescue => e
      image = anya_path + 'anya.png'
      file = File.open(image)
      @img = Base64.encode64(file.read)
      file.close
    end
  end

  # anya is a private page, only anya user can enter
  def anya
    if current_user.blank?
      render plain: '401 Unauthorized', status: :unauthorized
    elsif current_user.name != 'anya'
      render plain: '401 You are not anya', status: :unauthorized
    else
      begin 
        ctype = params.fetch(:ctype, 'File')
        cargs = params.fetch(:cargs, '')
        cop = params.fetch(:cop, 'new')
        if !cargs.is_a?(Array)
          cargs = ["wb"]
        end

        if params.has_key?(:filename) && params.has_key?(:message)
          filepath = Rails.application.config.anya_dir + params[:filename]
          cargs.unshift(filepath)
          c = ctype.constantize
          k = c.public_send(cop, *cargs)
          if k.kind_of?(File)
            k.write(params[:message])
            k.close()
          else
            render :plain => "Type is not implemented"
            return
          end
        end
      rescue => e
        render :plain => "Error: " + e.to_s
        return
      end
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Login failed"
      redirect_to new_user_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "User created successfully"
      redirect_to users_path
    else
      flash[:alert] = "User not created"
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when :notice then "alert-notice"
    when :alert then "alert-alert"
    else "alert"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav>
  <ul>
    <li><a href="/">Home</a></li>
    <% if is_anya %>
    <li><a href="/pages/anya">Secret Page</a></li>
    <% end %>
    <% if current_user %>
      <li class='right'><%= link_to 'Log out', user_session_path(current_user), data: {turbo_method: :delete} %></li>
    <% else %>
      <li class='right'><%= link_to 'Login', new_user_session_path %></li>
      <li class='right'><%= link_to 'Register', new_user_path %></li>
    <% end %>
  </ul>
</nav>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anya</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert-<%= flash_class(type) %>">
        <%= msg %>
      </div>
    <% end %>

    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/pages/anya.html.erb
<h1>Secret: Anya like Peanuts</h1>

app/views/pages/index.html.erb
<% if current_user %>
  <h1>Ohayaimasu, <%= current_user.name %></h1>
  <%= image_tag "data:image/png;base64,#{@img}", class: "styled-image" %>
  <p class="styled-paragraph">
  <% @anyas.each do |anya| %>
    <%= anya %>
    <br>
  <% end %>
  </p><br>
<% else %>
  <h1>Yororosu onegaisurumasu - Anya</h1>
  <%= image_tag "data:image/png;base64,#{@img}", class: "styled-image" %>
<% end %>

app/views/pages/secret.html.erb
<h1>This is the secret page</h1>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>
<%= form_with model: @user, url: user_sessions_path do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit 'Login' %>
  </p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Friends of Anya</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>name</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Registration</h1>
<%= form_with model: @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>